# Site settings
title: stevO Codes
header-img: img/home-bg.png
email: steve.telesmanic@gmail.com
copyright_name: stevoDEEBO
description: > # this means to ignore newlines until "baseurl:"
  steve's Adventures thru Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stevoDEEBO
learn_profile: stevoDEEBO
email_username: steve.telesmanic@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
