# Site settings
author: Stephen Telesmanic
title: stevO Codes
header-img: img/matrix.png
email: steve.telesmanic@gmail.com
copyright_name: Stephen Telesmanic
description: > # this means to ignore newlines until "baseurl:"
  steve's adventures thru coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  stevoDEEBO

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
